services:
  - type: web
    name: primesense
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir app app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
